import {
  Activity,
  ArrowLeftRight,
  BookOpen,
  Bot,
  Boxes,
  CalendarClock,
  Calculator,
  CandlestickChart,
  Cpu,
  Eye,
  FileBarChart2,
  FileCheck2,
  FileCode2,
  FileSearch,
  FileText,
  Globe2,
  History,
  House,
  Image as ImageIcon,
  Landmark,
  LayoutDashboard,
  ListTree,
  MessageSquare,
  MessagesSquare,
  Newspaper,
  Percent,
  Plug,
  Plus,
  Radar,
  Receipt,
  ReceiptText,
  Scale,
  Search,
  Settings,
  ShieldAlert,
  Ship,
  Sparkles,
  Store,
  UserCog,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Veri dosyalarında string olarak tutulan ikon adlarını gerçek bileşene bağlayan kayıt.
 * Tüm lucide paketini import etmek yerine açık liste kullanılır — bundle boyutu küçük kalır.
 */
const iconRegistry: Record<string, LucideIcon> = {
  Activity,
  ArrowLeftRight,
  BookOpen,
  Bot,
  Boxes,
  CalendarClock,
  Calculator,
  CandlestickChart,
  Cpu,
  Eye,
  FileBarChart2,
  FileCheck2,
  FileCode2,
  FileSearch,
  FileText,
  Globe2,
  History,
  House,
  Image: ImageIcon,
  Landmark,
  LayoutDashboard,
  ListTree,
  MessageSquare,
  MessagesSquare,
  Newspaper,
  Percent,
  Plug,
  Plus,
  Radar,
  Receipt,
  ReceiptText,
  Scale,
  Search,
  Settings,
  ShieldAlert,
  Ship,
  Sparkles,
  Store,
  UserCog,
  Wrench,
};

interface DynamicIconProps extends LucideProps {
  name: string;
}

export function DynamicIcon({ name, ...rest }: DynamicIconProps) {
  const IconComponent = iconRegistry[name];
  if (!IconComponent) return null;
  return <IconComponent {...rest} />;
}
