import {
  Activity,
  ArrowLeftRight,
  BookOpen,
  Bot,
  Boxes,
  Building2,
  CalendarClock,
  Calculator,
  CandlestickChart,
  Eye,
  FileBarChart2,
  FileCheck2,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Globe2,
  History,
  House,
  Image as ImageIcon,
  Landmark,
  Languages,
  LayoutDashboard,
  ListTree,
  MapPin,
  MessageSquare,
  MessageSquarePlus,
  MessagesSquare,
  Newspaper,
  PackageSearch,
  Palette,
  Percent,
  Plug,
  Plug2,
  Plus,
  Radar,
  Receipt,
  ReceiptText,
  Scale,
  Search,
  Settings,
  ShieldAlert,
  Ship,
  Sparkles,
  Store,
  SunMoon,
  Tags,
  TrendingUp,
  UserCircle2,
  UserCog,
  Users,
  Workflow,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Veri dosyalarında string olarak tutulan ikon adlarını gerçek bileşene bağlayan kayıt.
 * Tüm lucide paketini import etmek yerine açık liste kullanılır — bundle boyutu küçük kalır.
 * Yeni bir ikon adı veriye eklenirken buraya da eklenmelidir.
 */
const iconRegistry: Record<string, LucideIcon> = {
  Activity,
  ArrowLeftRight,
  BookOpen,
  Bot,
  Boxes,
  Building2,
  CalendarClock,
  Calculator,
  CandlestickChart,
  Eye,
  FileBarChart2,
  FileCheck2,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Globe2,
  History,
  House,
  Image: ImageIcon,
  Landmark,
  Languages,
  LayoutDashboard,
  ListTree,
  MapPin,
  MessageSquare,
  MessageSquarePlus,
  MessagesSquare,
  Newspaper,
  PackageSearch,
  Palette,
  Percent,
  Plug,
  Plug2,
  Plus,
  Radar,
  Receipt,
  ReceiptText,
  Scale,
  Search,
  Settings,
  ShieldAlert,
  Ship,
  Sparkles,
  Store,
  SunMoon,
  Tags,
  TrendingUp,
  UserCircle2,
  UserCog,
  Users,
  Workflow,
  Wrench,
};

interface DynamicIconProps extends LucideProps {
  name: string;
}

export function DynamicIcon({ name, ...rest }: DynamicIconProps) {
  const IconComponent = iconRegistry[name];
  if (!IconComponent) return null;
  return <IconComponent {...rest} />;
}
